In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
     "Date": [
        "2025-01-02","2025-01-05","2025-01-08","2025-01-10","2025-01-15",
        "2025-01-18","2025-01-22","2025-01-25","2025-01-28","2025-02-02",
        "2025-02-05","2025-02-08","2025-02-10","2025-02-12","2025-02-15",
        "2025-02-18","2025-02-20","2025-02-22","2025-02-25","2025-02-28"
    ],
    
    "Product Name":[
        "laptop","iphone","tablet","ipad","gaming pod",
        "iphone","laptop","mouse","headsets","keyboard",
        "ipad","iphone","laptop","iphone","monitor",
        "laptop","iphone","mouse","headsets","monitor"
    ],
    
    "Units Sold":[
        "10","20","40","5","17",
        "20","30","22","11","25",
        "16","33","80","6","21",
        "24","52","18","56","15"
    ],
    
    "Revenue":[5000,4000,2400,1200,7000,5000,2000,1800,3000,4500,
               1600,2100,8000,3600,2500,2700,10000,4200,3000,3200],
    "Region":[
        "North","South","East","West","North",
        "South","East","West","North","South",
        "East","West","North","South","East",
        "West","North","South","East","West"
    ],
    "Discount Offered (%)":[10,5,15,0,8,10,5,20,0,12,18,5,10,0,8,15,5,10,0,12],
    "Salesperson":[
        "Alice","Bob","Charlie","David","Alice",
        "Bob","Charlie","David","Alice","Bob",
        "Charlie","David","Alice","Bob","Charlie",
        "David","Alice","Bob","Charlie","David"
    ]
}

df = pd.DataFrame(data)
df

,Date,Product Name,Units Sold,Revenue,Region,Discount Offered (%),Salesperson
0,2025-01-02,laptop,10,5000,North,10,Alice
1,2025-01-05,iphone,20,4000,South,5,Bob
2,2025-01-08,tablet,40,2400,East,15,Charlie
3,2025-01-10,ipad,5,1200,West,0,David
4,2025-01-15,gaming pod,17,7000,North,8,Alice
5,2025-01-18,iphone,20,5000,South,10,Bob
6,2025-01-22,laptop,30,2000,East,5,Charlie
7,2025-01-25,mouse,22,1800,West,20,David
8,2025-01-28,headsets,11,3000,North,0,Alice
9,2025-02-02,keyboard,25,4500,South,12,Bob
10,2025-02-05,ipad,16,1600,East,18,Charlie
11,2025-02-08,iphone,33,2100,West,5,David
12,2025-02-10,laptop,80,8000,North,10,Alice
13,2025-02-12,iphone,6,3600,South,0,Bob
14,2025-02-15,monitor,21,2500,East,8,Charlie
15,2025-02-18,laptop,24,2700,West,15,David
16,2025-02-20,iphone,52,10000,North,5,Alice
17,2025-02-22,mouse,18,4200,South,10,Bob
18,2025-02-25,headsets,56,3000,East,0,Charlie
19,2025-02-28,monitor,15,3200,West,12,David

In [33]:
df["Date"] = pd.to_datetime(df["Date"])

df["Revenue After Discount"] = df["Revenue"] * (1 - df["Discount Offered (%)"]/100)

df["Performance"] = np.where(df["Revenue"] >= 5000, "High", "Low")

print("\nSales Dataset")
print(df)

Sales Dataset
         Date Product Name Units Sold  Revenue Region  Discount Offered (%)  \
0  2025-01-02       laptop         10     5000  North                    10
1  2025-01-05       iphone         20     4000  South                     5
2  2025-01-08       tablet         40     2400   East                    15
3  2025-01-10         ipad          5     1200   West                     0
4  2025-01-15   gaming pod         17     7000  North                     8
5  2025-01-18       iphone         20     5000  South                    10
6  2025-01-22       laptop         30     2000   East                     5
7  2025-01-25        mouse         22     1800   West                    20
8  2025-01-28     headsets         11     3000  North                     0
9  2025-02-02     keyboard         25     4500  South                    12
10 2025-02-05         ipad         16     1600   East                    18
11 2025-02-08       iphone         33     2100   West                     5
12 2025-02-10       laptop         80     8000  North                    10
13 2025-02-12       iphone          6     3600  South                     0
14 2025-02-15      monitor         21     2500   East                     8
15 2025-02-18       laptop         24     2700   West                    15
16 2025-02-20       iphone         52    10000  North                     5
17 2025-02-22        mouse         18     4200  South                    10
18 2025-02-25     headsets         56     3000   East                     0
19 2025-02-28      monitor         15     3200   West                    12

   Salesperson  Revenue After Discount Performance
0        Alice                  4500.0        High
1          Bob                  3800.0         Low
2      Charlie                  2040.0         Low
3        David                  1200.0         Low
4        Alice                  6440.0        High
5          Bob                  4500.0        High
6      Charlie                  1900.0         Low
7        David                  1440.0         Low
8        Alice                  3000.0         Low
9          Bob                  3960.0         Low
10     Charlie                  1312.0         Low
11       David                  1995.0         Low
12       Alice                  7200.0        High
13         Bob                  3600.0         Low
14     Charlie                  2300.0         Low
15       David                  2295.0         Low
16       Alice                  9500.0        High
17         Bob                  3780.0         Low
18     Charlie                  3000.0         Low
19       David                  2816.0         Low

In [34]:
print("\n1. Top 3 Revenue Transactions")
print(df.nlargest(3, "Revenue"))

1. Top 3 Revenue Transactions
         Date Product Name Units Sold  Revenue Region  Discount Offered (%)  \
16 2025-02-20       iphone         52    10000  North                     5
12 2025-02-10       laptop         80     8000  North                    10
4  2025-01-15   gaming pod         17     7000  North                     8

   Salesperson  Revenue After Discount Performance
16       Alice                  9500.0        High
12       Alice                  7200.0        High
4        Alice                  6440.0        High

In [35]:
print("\n2. Total Units Sold Per Product")
print(df.groupby("Product Name")["Units Sold"].sum())

2. Total Units Sold Per Product
Product Name
gaming pod           17
headsets           1156
ipad                516
iphone        202033652
keyboard             25
laptop         10308024
monitor            2115
mouse              2218
tablet               40
Name: Units Sold, dtype: object

In [36]:
print("\n3. Total Revenue After Discount")
print(df["Revenue After Discount"].sum())

3. Total Revenue After Discount
70578.0

In [37]:
print("\n4. Transaction with Highest Discount")
max_discount = df.loc[df["Discount Offered (%)"].idxmax()]
print(max_discount[["Product Name","Discount Offered (%)","Revenue After Discount"]])

4. Transaction with Highest Discount
Product Name               mouse
Discount Offered (%)          20
Revenue After Discount    1440.0
Name: 7, dtype: object

In [38]:
print("\n5. Highest Total Revenue by Salesperson")
sales_rev = df.groupby("Salesperson")["Revenue"].sum()
print(sales_rev)
print("Top:", sales_rev.idxmax())

5. Highest Total Revenue by Salesperson
Salesperson
Alice      33000
Bob        21300
Charlie    11500
David      11000
Name: Revenue, dtype: int64
Top: Alice

In [39]:
print("\n6. Average Discount by Salesperson")
print(df.groupby("Salesperson")["Discount Offered (%)"].mean())

6. Average Discount by Salesperson
Salesperson
Alice       6.6
Bob         7.4
Charlie     9.2
David      10.4
Name: Discount Offered (%), dtype: float64

In [40]:
print("\n7. Revenue by Region")
print(df.groupby("Region")["Revenue"].sum())

7. Revenue by Region
Region
East     11500
North    33000
South    21300
West     11000
Name: Revenue, dtype: int64

In [41]:
print("\n8. Alice's Best Region")
alice = df[df["Salesperson"]=="Alice"]
print(alice.groupby("Region")["Revenue"].sum())

8. Alice's Best Region
Region
North    33000
Name: Revenue, dtype: int64

In [45]:
print("\n10. High Performance Transactions")
print((df["Performance"]=="High").sum())

10. High Performance Transactions
5

In [46]:
print("\n11. North Region, No Discount")
north = df[(df["Region"]=="North") &
           (df["Discount Offered (%)"]==0)]
print(north.groupby("Salesperson")["Units Sold"].sum())

11. North Region, No Discount
Salesperson
Alice    11
Name: Units Sold, dtype: object

In [48]:
print("\n13. Average Revenue After Discount")
print(df.groupby(["Salesperson","Region"])["Revenue After Discount"].mean())

13. Average Revenue After Discount
Salesperson  Region
Alice        North     6128.0
Bob          South     3928.0
Charlie      East      2110.4
David        West      1949.2
Name: Revenue After Discount, dtype: float64

In [49]:
print("\n14. Cumulative Revenue")
df = df.sort_values(["Salesperson","Date"])
df["Cumulative Revenue"] = df.groupby("Salesperson")["Revenue"].cumsum()
print(df[["Date","Salesperson","Revenue","Cumulative Revenue"]])

14. Cumulative Revenue
         Date Salesperson  Revenue  Cumulative Revenue
0  2025-01-02       Alice     5000                5000
4  2025-01-15       Alice     7000               12000
8  2025-01-28       Alice     3000               15000
12 2025-02-10       Alice     8000               23000
16 2025-02-20       Alice    10000               33000
1  2025-01-05         Bob     4000                4000
5  2025-01-18         Bob     5000                9000
9  2025-02-02         Bob     4500               13500
13 2025-02-12         Bob     3600               17100
17 2025-02-22         Bob     4200               21300
2  2025-01-08     Charlie     2400                2400
6  2025-01-22     Charlie     2000                4400
10 2025-02-05     Charlie     1600                6000
14 2025-02-15     Charlie     2500                8500
18 2025-02-25     Charlie     3000               11500
3  2025-01-10       David     1200                1200
7  2025-01-25       David     1800                3000
11 2025-02-08       David     2100                5100
15 2025-02-18       David     2700                7800
19 2025-02-28       David     3200               11000

In [50]:
print("\n15. Top Two Transactions Per Salesperson")
df["Rank"] = df.groupby("Salesperson")["Revenue"]\
               .rank(method="dense", ascending=False)
print(df[df["Rank"]<=2][["Salesperson","Revenue","Rank"]])

15. Top Two Transactions Per Salesperson
   Salesperson  Revenue  Rank
12       Alice     8000   2.0
16       Alice    10000   1.0
5          Bob     5000   1.0
9          Bob     4500   2.0
14     Charlie     2500   2.0
18     Charlie     3000   1.0
15       David     2700   2.0
19       David     3200   1.0

In [51]:
print("\n16. Product-wise Cumulative Revenue")
df = df.sort_values(["Product Name","Date"])
df["Product Cumulative Revenue"] = \
    df.groupby("Product Name")["Revenue"].cumsum()
print(df[["Date","Product Name","Revenue",
          "Product Cumulative Revenue"]])

16. Product-wise Cumulative Revenue
         Date Product Name  Revenue  Product Cumulative Revenue
4  2025-01-15   gaming pod     7000                        7000
8  2025-01-28     headsets     3000                        3000
18 2025-02-25     headsets     3000                        6000
3  2025-01-10         ipad     1200                        1200
10 2025-02-05         ipad     1600                        2800
1  2025-01-05       iphone     4000                        4000
5  2025-01-18       iphone     5000                        9000
11 2025-02-08       iphone     2100                       11100
13 2025-02-12       iphone     3600                       14700
16 2025-02-20       iphone    10000                       24700
9  2025-02-02     keyboard     4500                        4500
0  2025-01-02       laptop     5000                        5000
6  2025-01-22       laptop     2000                        7000
12 2025-02-10       laptop     8000                       15000
15 2025-02-18       laptop     2700                       17700
14 2025-02-15      monitor     2500                        2500
19 2025-02-28      monitor     3200                        5700
7  2025-01-25        mouse     1800                        1800
17 2025-02-22        mouse     4200                        6000
2  2025-01-08       tablet     2400                        2400

In [52]:
print("\n17. Revenue Comparison")
comparison = df.groupby("Product Name")[["Revenue",
                                         "Revenue After Discount"]].mean()
print(comparison)

17. Revenue Comparison
              Revenue  Revenue After Discount
Product Name
gaming pod     7000.0                 6440.00
headsets       3000.0                 3000.00
ipad           1400.0                 1256.00
iphone         4940.0                 4679.00
keyboard       4500.0                 3960.00
laptop         4425.0                 3973.75
monitor        2850.0                 2558.00
mouse          3000.0                 2610.00
tablet         2400.0                 2040.00

In [53]:
print("\n18. Weighted Average Discount")

weighted_discount = df.groupby("Salesperson").apply(
    lambda x: np.average(
        x["Discount Offered (%)"],
        weights=x["Revenue"]
    ),
    include_groups=False
)

print(weighted_discount)

18. Weighted Average Discount

TypeError: <lambda>() got an unexpected keyword argument 'include_groups'

In [57]:
df["Regional total sales"] = df.groupby("Region")["Revenue"].sum
df

,Date,Product Name,Units Sold,Revenue,Region,Discount Offered (%),Salesperson,Revenue After Discount,Performance,Cumulative Revenue,Rank,Product Cumulative Revenue,Regional total sales
4,2025-01-15,gaming pod,17,7000,North,8,Alice,6440.0,High,12000,3.0,7000,<bound method GroupBy.sum of <pandas.core.grou...
8,2025-01-28,headsets,11,3000,North,0,Alice,3000.0,Low,15000,5.0,3000,<bound method GroupBy.sum of <pandas.core.grou...
18,2025-02-25,headsets,56,3000,East,0,Charlie,3000.0,Low,11500,1.0,6000,<bound method GroupBy.sum of <pandas.core.grou...
3,2025-01-10,ipad,5,1200,West,0,David,1200.0,Low,1200,5.0,1200,<bound method GroupBy.sum of <pandas.core.grou...
10,2025-02-05,ipad,16,1600,East,18,Charlie,1312.0,Low,6000,5.0,2800,<bound method GroupBy.sum of <pandas.core.grou...
1,2025-01-05,iphone,20,4000,South,5,Bob,3800.0,Low,4000,4.0,4000,<bound method GroupBy.sum of <pandas.core.grou...
5,2025-01-18,iphone,20,5000,South,10,Bob,4500.0,High,9000,1.0,9000,<bound method GroupBy.sum of <pandas.core.grou...
11,2025-02-08,iphone,33,2100,West,5,David,1995.0,Low,5100,3.0,11100,<bound method GroupBy.sum of <pandas.core.grou...
13,2025-02-12,iphone,6,3600,South,0,Bob,3600.0,Low,17100,5.0,14700,<bound method GroupBy.sum of <pandas.core.grou...
16,2025-02-20,iphone,52,10000,North,5,Alice,9500.0,High,33000,1.0,24700,<bound method GroupBy.sum of <pandas.core.grou...
9,2025-02-02,keyboard,25,4500,South,12,Bob,3960.0,Low,13500,2.0,4500,<bound method GroupBy.sum of <pandas.core.grou...
0,2025-01-02,laptop,10,5000,North,10,Alice,4500.0,High,5000,4.0,5000,<bound method GroupBy.sum of <pandas.core.grou...
6,2025-01-22,laptop,30,2000,East,5,Charlie,1900.0,Low,4400,4.0,7000,<bound method GroupBy.sum of <pandas.core.grou...
12,2025-02-10,laptop,80,8000,North,10,Alice,7200.0,High,23000,2.0,15000,<bound method GroupBy.sum of <pandas.core.grou...
15,2025-02-18,laptop,24,2700,West,15,David,2295.0,Low,7800,2.0,17700,<bound method GroupBy.sum of <pandas.core.grou...
14,2025-02-15,monitor,21,2500,East,8,Charlie,2300.0,Low,8500,2.0,2500,<bound method GroupBy.sum of <pandas.core.grou...
19,2025-02-28,monitor,15,3200,West,12,David,2816.0,Low,11000,1.0,5700,<bound method GroupBy.sum of <pandas.core.grou...
7,2025-01-25,mouse,22,1800,West,20,David,1440.0,Low,3000,4.0,1800,<bound method GroupBy.sum of <pandas.core.grou...
17,2025-02-22,mouse,18,4200,South,10,Bob,3780.0,Low,21300,3.0,6000,<bound method GroupBy.sum of <pandas.core.grou...
2,2025-01-08,tablet,40,2400,East,15,Charlie,2040.0,Low,2400,3.0,2400,<bound method GroupBy.sum of <pandas.core.grou...